project:
  type: book

book:
  title: "Введение в программирование на языке Python"
  page-footer:
    left: |
      Введение в программирование на языке Python
      Антон С.Смирнов.
    right: |
      Книга написана с помощью <a href="https://quarto.org/">Quarto</a>
  author: 
    name: "Антон С. Смирнов"
    orcid: "0000-0002-7510-1602"
    corresponding: true
    email: "smirnov_as@rsmu.ru"
    affiliations:
      - "Пироговский университет"
      - "МГНЦ им. Н.П. Бочкова"
  date: today
  date-format: long
  page-navigation: true
  repo-url: https://github.com/SmirnygaTotoshka/PISH_python
  repo-branch: main
  repo-actions: [issue]
  downloads: [pdf]
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/PISH1.qmd
    - chapters/PISH2.qmd
    - chapters/PISH3.qmd
    - chapters/PISH4.qmd
    - chapters/PISH5.qmd
    - chapters/PISH6.qmd
    - chapters/PISH7.qmd
    - chapters/PISH8.qmd
    - chapters/PISH9.qmd
    - chapters/PISH10.qmd
    - chapters/PISH11.qmd
    - chapters/PISH12.qmd
    - chapters/PISH13.qmd
    - chapters/PISH14.qmd
    - chapters/PISH15.qmd
    - summary.qmd
    - references.qmd

toc: true
toc-depth: 3
toc-title: "Оглавление"
fontsize: 14pt
linestretch: 1.5
geometry:
  - top=10mm
  - left=20mm
  - right=20mm
  - heightrounded
bibliography: references.bib
csl: gost-num-appear.csl
format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 350px
  pdf:
    documentclass: book
    pdf-engine: xelatex
    header-includes: |
      \usepackage[utf8]{inputenc}
      \usepackage[american,russian]{babel}
      \usepackage{hyperref}  
      \usepackage{unicode-math}

mainfont: Raleway
monofont: Raleway
sansfont: Raleway

editor: visual

