project:
  type: book

book:
  title: "Введение в программирование на языке Python"
  author: "Антон С. Смирнов"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - intro.qmd
    - PISH1.qmd
    - PISH2.qmd
    - PISH3.qmd
    - PISH4.qmd
    - PISH5.qmd
    - PISH6.qmd
    - PISH7.qmd
    - PISH8.qmd
    - PISH9.qmd
    - PISH10.qmd
    - PISH11.qmd
    - PISH12.qmd
    - PISH13.qmd
    - PISH14.qmd
    - PISH15.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
csl: gost-num-appear.csl
format:
  html:
    theme: cosmo

editor: visual

