# Предисловие {.unnumbered}

Это пособие подготовлено для занятий на курсе переподготовки по биоинформатике в рамках передовой инженерной школы Пироговского университета. Занятия проходят на кафедре биоинформатике медико-биологического факультета РНИМУ им. Н.И. Пирогова. Пособие расчитано на 15 занятий длительностью 4 академических часа (3 часа 10 минут).

Пособие не является исчерпывающим, а представляет из себя разбор базовых умений, необходимых для программирования на языке программирования Python. Названия глав соответствуют разобранным тематикам. первые два занятия будут посвящены азам теоретической информатики, без которых тяжело программировать в принципе. Третье занятие посвящено настройке среды для программирования, вашего рабочего места. Следующие шесть занятий посвящены базовым алгоитмический конструкциям языка. Затем два занятия посвящены парадигме объектно-ориентированного программирования, на которой основан язык. Последние четыре занятия посвящены самым широко используемым в науке библиотекам.

## Об авторе

1.  Смирнов Антон Сергеевич - ассистент кафедры биоинформатики МБФ РНИМУ им. Н.И. Пирогова, лаборант-исследователь лаборатории эпигенетики ожирения и диабета МГНЦ им. Н.П. Бочкова.