---
jupyter: python3
---

# Введение {.unnumbered}

Python является наиболее популярным языком программирования в биоинформатике. Как и всякий инструмент он обладает как рядом очевидных преимуществ, так и своими недостатками.

Достоинства:

-   Простота в освоении: Python обладает простым синтаксисом и динамическим определением типов, что упрощает проектирование программы. Кроме того, язык является интерпретируемым, что упрощает отладку.
-   Кроссплатформенность: с Python можно работать на всех самых распространенных операционных системах.
-   Удобное управление зависимостями: для языка разработаны целые программы и экосистемы, упрощающие использование чужого кода
-   Большое сообщество: на большинство проблем можно легко найти ответ в интернете.

Недостатки:

-   Проблемы с производительностью - код, написанный на Python, как правило работает сильно медленнее и потребляет больше ресурсов, чем аналоги, написанные на других языках
-   Global Interpreter Lock - усложняет написание параллельно выполняемого кода, что важно при обработке больщих данных
-   Проблемы с безопасностью - некоторые вещи, от которых зависит безопасность, в Python держаться только на соглашениях между разработчиками. Интерпретатор не следит за их исполнением.

Для овладения языком необходимы некоторый теоретический базис и постоянная практика, поэтому настоятельная рекомендация автора не ограничиваться данным пособием. Для начального уровня автор рекомендует следующие пособия:

1.  [Простой Python. Современный стиль программирования](https://cloud.itm-rsmu.ru/s/68x5oZkwM53c7F2), Билл Любанович @Lubanovich2016
2.  [Yandex Handbook. Основы Python](https://education.yandex.ru/handbook/python) @YandexPythonHandbook

##