---
jupyter: python3
---

# Заключение {.unnumbered}

В качестве закрепления попробуйте решить собственную исследовательскую или житейскую задачу с опорой на пройденный материал. Решение собственных задач с использованием программирования - лучший способ по-настоящему изучить его, так как чтобы выучить язык, на нём надо говорить. Данное пособие не является исчерпывающим, может содержать ошибки и быстро устареть. Изучайте профильную литературу, сайты и документацию. Не останавливайтесь на достигнутом!

## Контрольные вопросы

1.  Принципы кодирования информации компьютером

2.  Алгебра логики, логические операции и функции. Совершенные нормальные формы

3.  Python. Характеристика языка. Настройка среды разработчика

4.  Организация работы над кодом.

5.  Базовые конструкции языка. Типы данных.

6.  Арифметические и логические операции

7.  Строки и операции над ними

8.  Циклы и условия

9.  Функции. Виды функций.

10. Работа с файлами

11. Обработка исключительных ситуаций

12. Объектно-ориентированное программирование. Определение, принципы.

13. Numpy

14. Pandas

15. Matplotlib

16. Анализ данных на Python.