flowchart TB
    A["Данные"] --> B["Количественные"]
    A["Данные"] --> C["Категориальные"]
    B["Количественные"] --> D["Дискретные"]
    B["Количественные"] --> E["Непрерывные"]
    C["Категориальные"] --> F["Порядковые"]
    C["Категориальные"] --> G["Номинальные"]